# Generated by Django 3.0.7 on 2020-11-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201104_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='pic',
            field=models.ImageField(default=None, upload_to='static/images'),
        ),
    ]
