# Generated by Django 3.0.7 on 2020-11-09 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='category',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogs',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 11, 9, 14, 24, 0, 703240)),
        ),
    ]
